import os
from dotenv import load_dotenv

load_dotenv()

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_WHATSAPP_NUMBER = os.getenv("TWILIO_WHATSAPP_NUMBER")

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
GROQ_VISION_MODEL = os.getenv("GROQ_VISION_MODEL", "qwen/qwen3.6-27b")

GOOGLE_SHEET_ID = os.getenv("GOOGLE_SHEET_ID")
GOOGLE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")

NOTIFY_PHONE = os.getenv("NOTIFY_PHONE")
CRON_SECRET = os.getenv("CRON_SECRET")

USER2_PHONE = os.getenv("USER2_PHONE")
USER2_TICKETS_SHEET = os.getenv("USER2_TICKETS_SHEET", "Tickets_2")
USER2_SUMMARY_SHEET = os.getenv("USER2_SUMMARY_SHEET", "Summary_2")
